export interface Country {
  code: string
  name: string
  phonePrefix: string
  flag: string
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', phonePrefix: '+93', flag: '🇦🇫' },
  { code: 'AL', name: 'Albania', phonePrefix: '+355', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algeria', phonePrefix: '+213', flag: '🇩🇿' },
  { code: 'AR', name: 'Argentina', phonePrefix: '+54', flag: '🇦🇷' },
  { code: 'AU', name: 'Australia', phonePrefix: '+61', flag: '🇦🇺' },
  { code: 'AT', name: 'Austria', phonePrefix: '+43', flag: '🇦🇹' },
  { code: 'BD', name: 'Bangladesh', phonePrefix: '+880', flag: '🇧🇩' },
  { code: 'BE', name: 'Belgium', phonePrefix: '+32', flag: '🇧🇪' },
  { code: 'BR', name: 'Brazil', phonePrefix: '+55', flag: '🇧🇷' },
  { code: 'BG', name: 'Bulgaria', phonePrefix: '+359', flag: '🇧🇬' },
  { code: 'CA', name: 'Canada', phonePrefix: '+1', flag: '🇨🇦' },
  { code: 'CN', name: 'China', phonePrefix: '+86', flag: '🇨🇳' },
  { code: 'CO', name: 'Colombia', phonePrefix: '+57', flag: '🇨🇴' },
  { code: 'HR', name: 'Croatia', phonePrefix: '+385', flag: '🇭🇷' },
  { code: 'CZ', name: 'Czech Republic', phonePrefix: '+420', flag: '🇨🇿' },
  { code: 'DK', name: 'Denmark', phonePrefix: '+45', flag: '🇩🇰' },
  { code: 'EG', name: 'Egypt', phonePrefix: '+20', flag: '🇪🇬' },
  { code: 'FI', name: 'Finland', phonePrefix: '+358', flag: '🇫🇮' },
  { code: 'FR', name: 'France', phonePrefix: '+33', flag: '🇫🇷' },
  { code: 'DE', name: 'Germany', phonePrefix: '+49', flag: '🇩🇪' },
  { code: 'GR', name: 'Greece', phonePrefix: '+30', flag: '🇬🇷' },
  { code: 'HK', name: 'Hong Kong', phonePrefix: '+852', flag: '🇭🇰' },
  { code: 'HU', name: 'Hungary', phonePrefix: '+36', flag: '🇭🇺' },
  { code: 'IN', name: 'India', phonePrefix: '+91', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', phonePrefix: '+62', flag: '🇮🇩' },
  { code: 'IR', name: 'Iran', phonePrefix: '+98', flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraq', phonePrefix: '+964', flag: '🇮🇶' },
  { code: 'IE', name: 'Ireland', phonePrefix: '+353', flag: '🇮🇪' },
  { code: 'IL', name: 'Israel', phonePrefix: '+972', flag: '🇮🇱' },
  { code: 'IT', name: 'Italy', phonePrefix: '+39', flag: '🇮🇹' },
  { code: 'JP', name: 'Japan', phonePrefix: '+81', flag: '🇯🇵' },
  { code: 'JO', name: 'Jordan', phonePrefix: '+962', flag: '🇯🇴' },
  { code: 'KE', name: 'Kenya', phonePrefix: '+254', flag: '🇰🇪' },
  { code: 'KW', name: 'Kuwait', phonePrefix: '+965', flag: '🇰🇼' },
  { code: 'LB', name: 'Lebanon', phonePrefix: '+961', flag: '🇱🇧' },
  { code: 'MY', name: 'Malaysia', phonePrefix: '+60', flag: '🇲🇾' },
  { code: 'MX', name: 'Mexico', phonePrefix: '+52', flag: '🇲🇽' },
  { code: 'MA', name: 'Morocco', phonePrefix: '+212', flag: '🇲🇦' },
  { code: 'NL', name: 'Netherlands', phonePrefix: '+31', flag: '🇳🇱' },
  { code: 'NZ', name: 'New Zealand', phonePrefix: '+64', flag: '🇳🇿' },
  { code: 'NG', name: 'Nigeria', phonePrefix: '+234', flag: '🇳🇬' },
  { code: 'NO', name: 'Norway', phonePrefix: '+47', flag: '🇳🇴' },
  { code: 'OM', name: 'Oman', phonePrefix: '+968', flag: '🇴🇲' },
  { code: 'PK', name: 'Pakistan', phonePrefix: '+92', flag: '🇵🇰' },
  { code: 'PS', name: 'Palestine', phonePrefix: '+970', flag: '🇵🇸' },
  { code: 'PH', name: 'Philippines', phonePrefix: '+63', flag: '🇵🇭' },
  { code: 'PL', name: 'Poland', phonePrefix: '+48', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugal', phonePrefix: '+351', flag: '🇵🇹' },
  { code: 'QA', name: 'Qatar', phonePrefix: '+974', flag: '🇶🇦' },
  { code: 'RO', name: 'Romania', phonePrefix: '+40', flag: '🇷🇴' },
  { code: 'RU', name: 'Russia', phonePrefix: '+7', flag: '🇷🇺' },
  { code: 'SA', name: 'Saudi Arabia', phonePrefix: '+966', flag: '🇸🇦' },
  { code: 'SG', name: 'Singapore', phonePrefix: '+65', flag: '🇸🇬' },
  { code: 'ZA', name: 'South Africa', phonePrefix: '+27', flag: '🇿🇦' },
  { code: 'KR', name: 'South Korea', phonePrefix: '+82', flag: '🇰🇷' },
  { code: 'ES', name: 'Spain', phonePrefix: '+34', flag: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka', phonePrefix: '+94', flag: '🇱🇰' },
  { code: 'SE', name: 'Sweden', phonePrefix: '+46', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', phonePrefix: '+41', flag: '🇨🇭' },
  { code: 'SY', name: 'Syria', phonePrefix: '+963', flag: '🇸🇾' },
  { code: 'TW', name: 'Taiwan', phonePrefix: '+886', flag: '🇹🇼' },
  { code: 'TH', name: 'Thailand', phonePrefix: '+66', flag: '🇹🇭' },
  { code: 'TR', name: 'Turkey', phonePrefix: '+90', flag: '🇹🇷' },
  { code: 'UA', name: 'Ukraine', phonePrefix: '+380', flag: '🇺🇦' },
  { code: 'AE', name: 'United Arab Emirates', phonePrefix: '+971', flag: '🇦🇪' },
  { code: 'GB', name: 'United Kingdom', phonePrefix: '+44', flag: '🇬🇧' },
  { code: 'US', name: 'United States', phonePrefix: '+1', flag: '🇺🇸' },
  { code: 'VN', name: 'Vietnam', phonePrefix: '+84', flag: '🇻🇳' },
  { code: 'YE', name: 'Yemen', phonePrefix: '+967', flag: '🇾🇪' },
]

export const CURRENCIES = [
  { code: 'USD', name: 'US Dollar', symbol: '$' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'GBP', name: 'British Pound', symbol: '£' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك' },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: '£' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
]

